import './globals.css'
import Header from "../components/Header.js";
import Footer from "../components/Footer.js";

export const metadata = {
  title: 'Finesse Tissue',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Header />
        {children}
        <Footer />
        </body>
    </html>
  )
}
